### ISSUE TITLE
Downloading pictures with highest possible resolution

### ISSUE THREAD

**Issue by jacekmusial** [met94/MessengerChatMediaDownloader#1]
Is it possible to change default 480x480 resolution of downloaded pictures? Or is it rather impossible because this project use [unoffical api](https://github.com/Schmavery/facebook-chat-api)? 
Only hope to get best media quality is to either use https://developers.facebook.com/docs/messenger-platform or write selenium based scrapper?

**Comment by met94** [comment]
Take a look into https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#listen Attachments table. According to the table there are the following fields available for photo attachments: ID, filename, thumbnailUrl, previewUrl, previewWidth, previewHeight, largePreviewUrl, largePreviewWidth, largePreviewHeight. The one I use to download a photo is largePreviewUrl but I haven't really checked other fields, perhaps one of them provides better resolution.

**Comment by met94** [comment]
Just came across this method https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#resolvePhotoUrl. This is probably the solution.

**Comment by jacekmusial** [comment]
Thank you, I will test both methods shortly and create a MR. Currently just have problems downloading any media from the chats and after two tries my messenger account gets blocked and have to reset the password, so it's not easy.

**Comment by outpoints** [comment]
Did you ever fix this issue? @jacekmusial 
Trying to archive all my photos with my fiancee that we've sent to each other over the past five years 😅

**Comment by jacekmusial** [comment]
@outpoints @met94 Thank you for your message outpoints, I have completely forgot about it. 
Have look at https://github.com/met94/MessengerChatMediaDownloader/pull/2. But please be aware that I have to test delays , because Facebook is eager to block people.

**Comment by outpoints** [comment]
Thanks! @jacekmusial 
Will test out delays and see what works best!
Appreciate it!

**Comment by outpoints** [comment]
Be careful @jacekmusial my Facebook account was just disabled...
My profile disappeared off of Messenger for everyone and now they are saying this after submitting an appeal.
![image](https://user-images.githubusercontent.com/12377381/103958505-02947400-5102-11eb-9c10-946869aee020.png)

I hope they actually do unban me but it's Facebook so who knows 😖

**Comment by jacekmusial** [comment]
@outpoints @jacekmusial I have found better solution, which worked for me. I was able to download 11k medias from one group chat. Open Chrome, log to the Messenger, open chat, open latest media and execute this script in the console https://gist.github.com/jacekmusial/5021754c01cdc26aa6183619e31aef2a

I hope you will get your account soon outpoints!

**Comment by outpoints** [comment]
I got my account back! This doesn't change which media is currently selected. It only spams the download for the same image, will need to figure out the class name for the next button 😅 @jacekmusial

**Comment by jacekmusial** [comment]
I am happy for you @outpoints. It worked for me on several occasions, but I suspect they might change class name. Yes, I have seen a few duplicated images but never was able to resolve it. Do you have any idea what might be causing it?

**Comment by outpoints** [comment]
> 
> 
> I am happy for you @outpoints. It worked for me on several occasions, but I suspect they might change class name. Yes, I have seen a few duplicated images but never was able to resolve it. Do you have any idea what might be causing it?

Yes! It was simply removing ` downloadButton[0].click();` on line 13 that fixed it!
I was able to download 16k images via that script :)
